### ISSUE TITLE
如何配置

### ISSUE THREAD

**Issue by wuge0** [ChirmyRam/E5-Rclone-Actions-Repo#6]
rclone.zip密码是啥
我该如何配置rclone.conf文件

**Comment by ChirmyRam** [comment]
压缩包密码是自己压缩时设定的。rclone挂载OneDrive详见百度教程。

**Comment by wuge0** [comment]
是要服务器先配置好rclone.conf再上传GitHub是吧

**Comment by ChirmyRam** [comment]
仔细阅读README
